site_name: QGIS Earth Engine Plugin
site_description: Documentation for the QGIS Earth Engine Plugin
site_url: https://gee-community.github.io/qgis-earthengine-plugin/
repo_url: https://github.com/gee-community/qgis-earthengine-plugin
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
    - toc.integrate
  language: en
  logo: https://github.com/gee-community/qgis-earthengine-plugin/blob/main/ee_plugin/icons/earth-engine.svg?raw=true
  favicon: https://github.com/gee-community/qgis-earthengine-plugin/blob/main/ee_plugin/icons/earth-engine.svg?raw=true
    

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Installation: installation.md
  - Usage: usage.md
  - Troubleshooting: troubleshooting.md
  - Tutorials:
    - Downloading Images: tutorials/downloading_images.md
    - Building a Workflow: tutorials/building_a_workflow.md
    - Visualizing Data: tutorials/visualizing_data.md

plugins:
  - search
  - git-revision-date-localized:
      type: date
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_themed: false
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false


repo_name: gee-community/qgis-earthengine-plugin

watch:
  - README.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gee-community/qgis-earthengine-plugin

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.snippets:
      base_path:
        - .
        - docs
      check_paths: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons