site_name: QGIS Earth Engine Plugin
site_description: Documentation for the QGIS Earth Engine Plugin
site_url: https://gee-community.github.io/qgis-earthengine-plugin/
repo_url: https://github.com/gee-community/qgis-earthengine-plugin
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
    - toc.integrate
    - navigation.footer      
    - content.action.history  
    - content.metadata
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow  
  language: en
  logo: https://github.com/gee-community/qgis-earthengine-plugin/blob/main/ee_plugin/icons/earth-engine.svg?raw=true
  favicon: https://github.com/gee-community/qgis-earthengine-plugin/blob/main/ee_plugin/icons/earth-engine.svg?raw=true
    

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Installation: installation.md
  - Usage: usage.md
  - Troubleshooting: troubleshooting.md
  - Tutorials:
    - Downloading Images: tutorials/downloading_images.md
    - Building a Workflow: tutorials/building_a_workflow.md
    - Visualizing Data: tutorials/visualizing_data.md

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: false
      enable_creation_date: true

  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_themed: false
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false
  - git-committers:
      repository: gee-community/qgis-earthengine-plugin
      branch: main


repo_name: gee-community/qgis-earthengine-plugin

# Copyright
copyright: Copyright &copy; 2025  Antony Barja (geografope)
watch:
  - README.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gee-community/qgis-earthengine-plugin
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/squidfunk
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/squidfunk/mkdocs-material/
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/mkdocs-material/
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/squidfunk.bsky.social
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@squidfunk
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/squidfunk
extra_css:
   - stylesheets/gbextra.css
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.snippets:
      base_path:
        - .
        - docs
      check_paths: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true      
      line_spans: __span        
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences  
