# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ee_plugin/ui/dailog2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

margins = [10] * 4


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(554, 653)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 551, 651))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(*margins)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 19, 541, 41))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setContentsMargins(*margins)
        self.formLayout.setObjectName("formLayout")
        self.addGEEFeatureCollectionToMapLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.addGEEFeatureCollectionToMapLabel.setObjectName(
            "addGEEFeatureCollectionToMapLabel"
        )
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.addGEEFeatureCollectionToMapLabel
        )
        self.addGEEFeatureCollectionToMapLineEdit = QtWidgets.QLineEdit(
            self.formLayoutWidget
        )
        self.addGEEFeatureCollectionToMapLineEdit.setObjectName(
            "addGEEFeatureCollectionToMapLineEdit"
        )
        self.formLayout.setWidget(
            0,
            QtWidgets.QFormLayout.FieldRole,
            self.addGEEFeatureCollectionToMapLineEdit,
        )
        self.verticalLayout.addWidget(self.groupBox)

        #
        self.groupBox_2 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 20, 541, 101))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(
            QtWidgets.QFormLayout.ExpandingFieldsGrow
        )
        self.formLayout_2.setContentsMargins(*margins)
        self.formLayout_2.setObjectName("formLayout_2")
        self.nameLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.formLayout_2.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit
        )
        self.valueLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.valueLabel.setObjectName("valueLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.valueLabel)
        self.valueLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.valueLineEdit.setObjectName("valueLineEdit")
        self.formLayout_2.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.valueLineEdit
        )
        self.verticalLayout.addWidget(self.groupBox_2)

        #
        self.groupBox_3 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(0, 20, 541, 101))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setFieldGrowthPolicy(
            QtWidgets.QFormLayout.AllNonFixedFieldsGrow
        )
        self.formLayout_3.setContentsMargins(*margins)
        self.formLayout_3.setObjectName("formLayout_3")
        self.nameLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.nameLabel_2.setObjectName("nameLabel_2")
        self.formLayout_3.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.nameLabel_2
        )
        self.dateEdit = QtWidgets.QDateEdit(self.formLayoutWidget_3)
        self.dateEdit.setObjectName("dateEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dateEdit)
        self.valueLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.valueLabel_2.setObjectName("valueLabel_2")
        self.formLayout_3.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.valueLabel_2
        )
        self.dateEdit_2 = QtWidgets.QDateEdit(self.formLayoutWidget_3)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dateEdit_2)
        self.verticalLayout.addWidget(self.groupBox_3)

        #
        self.groupBox_4 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_4.setObjectName("groupBox_4")
        self.mExtentGroupBox = gui.QgsExtentGroupBox(self.groupBox_4)
        self.mExtentGroupBox.setGeometry(QtCore.QRect(0, 10, 541, 171))
        self.mExtentGroupBox.setObjectName("mExtentGroupBox")
        self.verticalLayout.addWidget(self.groupBox_4)

        #
        self.groupBox_5 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_5)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(0, 20, 541, 54))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setFormAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop
        )
        self.formLayout_4.setContentsMargins(*margins)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label.setObjectName("label")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.mColorButton = gui.QgsColorButton(self.formLayoutWidget_4)
        self.mColorButton.setObjectName("mColorButton")
        self.formLayout_4.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.mColorButton
        )
        self.verticalLayout.addWidget(self.groupBox_5)

        #
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok
        )
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        #

        for i, size in enumerate((1, 2, 2, 3, 1, 1)):
            self.verticalLayout.setStretch(i, size)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Source"))
        self.addGEEFeatureCollectionToMapLabel.setToolTip(
            _translate("Dialog", "This is a tooltip!")
        )
        self.addGEEFeatureCollectionToMapLabel.setWhatsThis(
            _translate(
                "Dialog", 'This is "WhatsThis"! <a href="http://google.com">Link</a>'
            )
        )
        self.addGEEFeatureCollectionToMapLabel.setText(
            _translate("Dialog", "Add GEE Feature Collection to Map")
        )
        self.groupBox_2.setTitle(_translate("Dialog", "Filter by Properties"))
        self.nameLabel.setText(_translate("Dialog", "Name"))
        self.valueLabel.setText(_translate("Dialog", "Value"))
        self.groupBox_3.setTitle(_translate("Dialog", "Filter by Dates"))
        self.nameLabel_2.setText(_translate("Dialog", "Start"))
        self.valueLabel_2.setText(_translate("Dialog", "End"))
        self.groupBox_4.setTitle(_translate("Dialog", "Filter by Coordinates"))
        self.groupBox_5.setTitle(_translate("Dialog", "Visualization"))
        self.label.setText(_translate("Dialog", "Color"))


from qgis import gui


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
