name: Setup extlibs
description: Install and clean up plugin dependencies

runs:
  using: "composite"
  steps:
    - name: Install plugin dependencies into extlibs
      shell: bash
      run: |
        ./scripts/build_extlibs.sh
