# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: package-plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install qgis-plugin-ci
    - name: Install plugin dependencies into extlibs
      run: |
        mkdir -p ee_plugin/extlibs
        pip install -r requirements.txt -t ee_plugin/extlibs
        find ee_plugin/extlibs -type f \( -name '*.so' -o -name '*.pyd' -o -name '*.dylib' \) -delete
        find ee_plugin/extlibs -type d -name __pycache__ -exec rm -rf {} +

    - name: Package QGIS Plugin with qgis-plugin-ci
      run: |
        qgis-plugin-ci package 0.0.0-dev \
          --asset-path ee_plugin/extlibs \
          --allow-uncommitted-changes
              
    - name: Check plugin package size
      run: |
        max_size=$((50 * 1024 * 1024))  # 50 MB
        actual_size=$(stat --format="%s" ee_plugin.*.zip)
        if [ "$actual_size" -gt "$max_size" ]; then
          echo "Plugin package size exceeds 50MB limit."
          exit 1
        fi
   
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ee_plugin-${{ matrix.os }}.zip
        path: ee_plugin.zip
  package:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v4.1.7
        
        
