name: 📦 Release

on:
  push:
    branches:
      - main
  release:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: googleapis/release-please-action@v4
        id: rp
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/release-please-config.json

  package-and-publish:
    if: github.event_name == 'release' && startsWith(github.event.release.tag_name, 'v')
    needs: release-please
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Extract version
        run: |
          VERSION="${{ github.event.release.tag_name#v }}"
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"

      - name: Install deps
        run: |
          pip install qgis-plugin-ci
          pip install -r requirements.txt -t ee_plugin/extlibs

      - name: Package & Release plugin
        run: |
          qgis-plugin-ci release "$VERSION" \
            --release-tag "${{ github.event.release.tag_name }}" \
            --github-token "${{ secrets.GITHUB_TOKEN }}" \
            --osgeo-username "${{ secrets.OSGEO_USER }}" \
            --osgeo-password "${{ secrets.OSGEO_PASS }}" \
            --asset-path ee_plugin/extlibs \
            --allow-uncommitted-changes