name: Release QGIS Plugin

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install qgis-plugin-ci

      - name: Vendor extlibs dependencies
        run: |
          # Install required Python packages into ee_plugin/extlibs
          pip install -r requirements.txt -t ee_plugin/extlibs
          find ee_plugin/extlibs -type d -name __pycache__ -exec rm -rf {} +
          # Optionally clean metadata folders
          find ee_plugin/extlibs -type d -name "*.dist-info" -exec rm -rf {} +

      - name: Get tag version
        run: |
          # Strip "refs/tags/" prefix, then leading "v"
          raw="${GITHUB_REF#refs/tags/}"
          export VERSION_TAG="${raw}"
          echo "TAG_NAME=$VERSION_TAG" >> $GITHUB_ENV

      - name: Package plugin
        run: |
          qgis-plugin-ci package "$VERSION_TAG" \
            --asset-path ee_plugin/extlibs

      - name: Package and publish release
        run: |
          qgis-plugin-ci package "$TAG_NAME" \
            --asset-path ee_plugin/extlibs
          qgis-plugin-ci release "$TAG_NAME" \
            --github-token ${{ secrets.GITHUB_TOKEN }} \
            --osgeo-user ${{ secrets.OSGEO_USER }} \
            --osgeo-pass ${{ secrets.OSGEO_PASS }} \