name: package-plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install qgis-plugin-ci

    - name: Setup extlibs
      uses: ./.github/actions/setup-extlibs

    - name: Package QGIS Plugin with qgis-plugin-ci
      run: |
        qgis-plugin-ci package 0.0.0-dev \
          --asset-path ee_plugin/extlibs \
          --allow-uncommitted-changes
              
    - name: Check plugin package size
      run: |
        max_size=$((50 * 1024 * 1024))  # 50 MB
        actual_size=$(stat --format="%s" ee_plugin.*.zip)
        if [ "$actual_size" -gt "$max_size" ]; then
          echo "Plugin package size exceeds 50MB limit."
          exit 1
        fi
        